spring:
  application:
    name: config-server-defualt

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka


  instance:
    hostname: localhost
    prefer-ip-address: true
